# Generated by Django 3.2.8 on 2022-01-24 13:25

from django.db import migrations, models
import Webpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userfaceimage',
            name='image',
            field=models.ImageField(upload_to=Webpage.models.content_file_name),
        ),
    ]
