# Generated by Django 3.2.8 on 2022-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0004_user_weight_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weight_height',
            name='height',
            field=models.IntegerField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_weight_height',
            name='weight',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
