# Generated by Django 3.2.8 on 2022-04-16 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0005_auto_20220416_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weight_height',
            name='height',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='user_weight_height',
            name='weight',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(400)]),
        ),
    ]
