# Generated by Django 3.2.8 on 2022-04-16 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webpage', '0006_auto_20220416_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weight_height',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
