# Generated by Django 3.2.8 on 2022-04-16 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0007_alter_user_weight_height_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weight_height',
            name='height',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
    ]
